cache:
    directories:
        - $HOME/perl_modules
        - $HOME/tidyall_d

sudo: false
language: perl
perl:
    - 'blead'
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'
    - '5.18'
    - '5.16'
    - '5.14'

matrix:
    allow_failures:
        - perl: 'blead'
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
install:
    - cpanm --quiet --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support Perl::Critic Perl::Tidy Test::Code::TidyAll
    - cpanm --quiet --skip-satisfied Digest File::Find::Object
script:
    - prove t/*.t
